{{- if .Values.app.cloudSqlSidecar.enabled }}
apiVersion: v1
kind: Secret
metadata:
    name: cloudsql-credentials
    namespace: "{{ .Values.app.name }}-{{ .Values.app.env }}"
type: Opaque
data:
    service-account.json: {{ .Values.app.cloudSqlSidecar.serviceAccountSecret }}
{{- end }}