apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: "{{ .Values.app.name }}-{{ .Values.app.env }}"
  labels:
    app: {{ .Values.app.name }}
    environment: {{ .Values.app.env }}
spec:
{{- if .Values.service.noneclusterip }}
  clusterIP: None
{{- end }}
  type: "{{ .Values.controller.service.type }}"
  ports:
  - name: http
    port: 80
    targetPort: 9000
  selector:
    app: {{ .Values.app.name }}
    environment: {{ .Values.app.env }}
