apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: "{{ .Values.app.name }}-{{ .Values.app.env }}"
  labels:
    app: {{ .Values.app.name }}
    environment: {{ .Values.app.env }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      environment: {{ .Values.app.env }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        environment: {{ .Values.app.env }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image }}
          env:
            - name: APP_NAME
              value: {{ .Values.app.name }}
            - name: APP_HOST
              value: {{ .Values.app.host }}
            - name: APP_ENV
              value: {{ .Values.app.env }}
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "10"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
