{{- if .Values.grafanaIngress.enabled }}
{{ $appName := .Values.grafanaIngress.appName }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.grafanaIngress.appName }}
  namespace: {{ .Values.grafanaIngress.namespaces }}
  {{- with .Values.grafanaIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.grafanaIngress.tls }}
  tls:
    {{- range .Values.grafanaIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.grafanaIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path | quote }}
            backend:
              serviceName: {{ $appName }}
              servicePort: 80
    {{- end }}
{{- end }}
